name: Docker CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
# Triggers the workflow on push events for the master branch only,
# or all pull request events:
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
# This workflow contains two jobs, "build" and "mathcomp", for demo purposes;
# a typical workflow would only contain one of them:
# keep a job similar to "build" if pulling an image with coq+bignums is enough
# or keep a job similar to "mathcomp" if your project relies on mathcomp, so
# an image with coq+bignums+mathcomp will be pulled.
jobs:
  build:
    # The type of runner that the job will run on;
    # the OS must be GNU/Linux to be able to use the docker-coq-action.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Browse URL: https://github.com/coq-community/docker-coq/wiki#supported-tags
        # to get the list of supported (coq, ocaml) versions in coqorg/coq.
        coq_version:
          - '8.15'
          - 'dev'
        ocaml_version:
          - '4.07-flambda'
      # at most 20 concurrent jobs per free account:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limits
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        # See https://github.com/coq-community/docker-coq-action#readme
        # for details on docker-coq-action's syntax and provided features.
        with:
          opam_file: 'coq.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'
